# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
import json
import uuid
import re

from typing import List, Dict  # noqa: F401

from ..base_model import Model
from .. import util


class Data(Model):
    """NOTE: This class is auto generated by Cloud Events Generator
    (https://github.com/michaelawyu/cloud-events-generator)
    using modified templates from OpenAPI generator
    (https://github.com/OpenAPITools/openapi-generator)
    under Apache 2.0 License.

    Do not edit the class manually.
    """

    def __init__(self, bypass_check=False, videoId=None):  # noqa: E501
        """Data - a model defined in Cloud Events Generator

        :param videoId: The videoId of this Data.  # noqa: E501
        :type videoId: str
        """
        self.openapi_types = {
            'videoId': str
        }

        self.attribute_map = {
            'videoId': 'videoId'
        }
        if not bypass_check:
                self.videoId = videoId
        else:
                self._videoId = videoId

    @classmethod
    def from_dict(cls, dikt) -> 'Data':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: An instance of this Data.  # noqa: E501
        :rtype: Data
        """
        return util.deserialize_model(dikt, cls)

    @property
    def videoId(self):
        """Gets the videoId of this Data.

          # noqa: E501

        :return: The videoId of this Data.
        :rtype: str
        """
        return self._videoId

    @videoId.setter
    def videoId(self, videoId):
        """Sets the videoId of this Data.

          # noqa: E501

        :param videoId: The videoId of this Data.
        :type videoId: str
        """


        self._videoId = videoId

